# Site settings
title: "Jiayu_Wang (王嘉裕)"
description: "Jiayu_Wang (王嘉裕)"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jiayu Wang"
resume_title:                   "Ph.D. Candidate in Mechanical Engineering"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "wangj12@tcd.ie"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+353-83-089-1937"
resume_contact_address:         "College Green, Dubin 2, D02 PN40, Ireland"

resume_header_contact_info:     "College Green, Dubin 2, D02 PN40, Ireland •+353-83-089-1937 • wangj12@tcd.ie"
display_header_contact_info:    "true"

resume_header_intro: "<p style=text-align:justify> Jiayu obtained his Bachelor's degree in Flight Vehicle Propulsion Engineering from Northwestern Polytechnical University, Xi'an in 2018. Subsequently, he was conferred his Master's degrees in Aeronautical Engineering from the Moscow Aviation Institute, Moscow and Shanghai Jiao Tong University, Shanghai in 2020 and 2021, respectively. Jiayu was honored as an Outstanding Graduate by the Shanghai Jiao Tong University in 2021. Currently, Jiayu is serving as a Ph.D. candidate in the Department of Mechanical, Manufacturing, and Biomedical Engineering at Trinity College Dublin, University of Dublin. Jiayu's research interests are diverse and evolving. He has previously concentrated on noise source localization and advanced array testing techniques. Presently, his focus is on developing innovative micro-perforated panel absorber technologies for sound absorption. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
#resume_section_experience:               true
resume_section_education:                 true
#resume_section_projects:                 true
resume_section_publications:              true
resume_section_techanical_skills:         true
#resume_section_recognition:              true
resume_section_links:                     true
#resume_section_associations:             true
# resume_section_interests:               true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  #resume_github_url:            "https://github.com/jglovier/resume-template"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      false

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts

theme: jekyll-theme-cayman
