# Site settings
title: "Jiayu_Wang (王嘉裕)"
description: "Jiayu_Wang (王嘉裕)"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Jiayu Wang"
resume_title:                   "Ph.D. Candidate in Mechanical Engineering"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "wangj12@tcd.ie"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+353-83-089-1937"
resume_contact_address:         "College Green, Dubin 2, D02 PN40, Ireland"

resume_header_contact_info:     "College Green, Dubin 2, D02 PN40, Ireland •+353-83-089-1937 • wangj12@tcd.ie"
display_header_contact_info:    "true"

resume_header_intro: "<p style=text-align:justify> Jiayu received his bachelor’s in flight vehicle propulsion engineering from Northwestern Polytechnical University, Xi’an in 2014. He rescived his M.S. degrees in aeronautical Engineering from Moscow Aviation Institute, Moscow and Shanghai Jiao Tong University, Shanghai in 2020 and 2021, respectively. Notably, Jiayu was awarded the Shanghai Jiao Tong University Outstanding Graduate in 2021. Currently, he works as a Ph.D. candidate in Department of Mechanical, Manufacturing and Biomedical Engineering, Trinity College Dublin, the University of Dublin under the support of China Scholarship Council (CSC)-Trinity College Dublin Joint Scholarship (2021). Jiayu's research interests are wide-ranging. Previously he focused on noise source localisation and advanced array testing techniques. Now he is trying to understand the sound absorption mechanism of micro-perforated panels from a vibration-acoustic viewpoint. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
#resume_section_experience:               true
resume_section_education:                 true
#resume_section_projects:                 true
resume_section_publications:              true
resume_section_technical_skills:          true
#resume_section_recognition:              true
#resume_section_links:                    true
#resume_section_associations:             true
# resume_section_interests:               true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  #resume_github_url:            "https://github.com/jglovier/resume-template"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      false

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts

theme: jekyll-theme-cayman
